---
output:
  html_document:
    fig_caption: yes
    highlight: haddock
    theme: cosmo
    toc: yes
---
Film Performance 11/2003 - 11/2015
==================================

_Aaron Foss_
------------
```{r echo=FALSE, message=FALSE, warning=FALSE, packages}
# Load all of the packages that you end up using
# in your analysis in this code chunk.

# Notice that the parameter "echo" was set to FALSE for this code chunk.
# This prevents the code from displaying in the knitted HTML output.
# You should set echo=FALSE for all code chunks in your file.

setwd("~/../version-control/Film-EDA")  # set my working directory
graphics.off() # close charts
rm(list = ls(all = TRUE)) #clear objects from memory

library(ggplot2)
library(rjson)
library(data.table) # this is a great library for data manipulation
library(gridExtra)
library(knitr)
library(GGally)
library(RColorBrewer)

setwd("~/../version-control/Film-EDA")  # set my working directory
source(paste(getwd(), '/eda_assist_functions.R', sep = ''))#loads additional functions

```

```{r echo=FALSE, Load_the_Data}
# Load the Data

# This will generate a list fo json docs rather than a data frame.  
# The structure is a little more flexible and allows for less sparsity.  
# Specific analyses may prepare different data frames as needed and will be noted
file <- 'boxoffice_mojo_metacritic_merge.json'
con = file(file, "r")
movie_data <- readLines(con, -1L)
close(con)

# clean environment
rm(file)
rm(con)

# builds a dataframe of my selected attributes (there are more in the json)
suppressWarnings (movie_df <- lapply(movie_data, make_film_frame))
movie_df <- rbindlist(movie_df)

# limit to films in wide release
movie_df <- movie_df[max_theaters > 1000, ]

# coerce release dates to date format
movie_df$release_date <- as.Date(movie_df$release_date, '%Y-%m-%d')

#filter out some re-releases
movie_df <- movie_df[release_date > '2003-10-31', ]

#coerce week to ordered variable 
movie_df$week <- factor(movie_df$week,
                        levels = sort(levels(movie_df$week)), ordered = F)

# #coerce release_mo_wk to ordered variable
# movie_df$release_mo_wk <- factor(movie_df$release_mo_wk,
#                                  levels = sort(levels(movie_df$release_mo_wk)),
#                                  ordered = T)

# coerce rating to ordered variable
movie_df$mpaa_rating <- factor(movie_df$mpaa_rating,
                                 levels = c('G',
                                            'PG', 
                                            'PG-13', 
                                            'R', 
                                            'NC-17',
                                            'Unrated', 
                                            'Not Yet Rated',
                                            'Unknown'), 
                               ordered = T)

# order data for faster searches
setkey(movie_df, title, relative_week)

# make year variable to buid weekly composites
movie_df[, year := as.numeric(substr(release_date, 1, 4))]

#filter out pre-11/2003
movie_df <- movie_df[year + as.numeric(week) / 52 > (2003 + 11 * 4.1 / 52), ]

# make variable for percentage of opening weekly gross
movie_df[, opening_gross := weekly_gross[1], by = title]
movie_df[, pct_opening_gross := weekly_gross / opening_gross]


# make variable for percentage of opening weekly theaters
movie_df[, opening_theaters := weekly_theaters[1], by = title]
movie_df[, pct_opening_theaters := weekly_theaters / opening_theaters]

# make variable for theater efficiency
movie_df[, daily_theater_eff := weekly_gross / (weekly_theaters * weekly_days)]

# make relative weekly competition variables (gross, critics and theaters)
# of other film attributes in a particular year/week
movie_df[, comp_week_gross := sum(weekly_gross), by = list(year, week)]
movie_df[, comp_week_gross := comp_week_gross - weekly_gross]
movie_df[, comp_week_critics := sum(critics_avg, na.rm = T), by = list(year, week)]
movie_df[, comp_week_critics := comp_week_critics - critics_avg]
movie_df[, comp_week_theaters := sum(weekly_theaters, na.rm = T),by = list(year, week)]
movie_df[, comp_week_theaters := comp_week_theaters - weekly_theaters]
# summary(m1 <- lm((weekly_gross)/gross~as.numeric(weekly_theaters/cum_theaters)+rel_week_cash+(rel_week_critics)+critics_avg+release_mo_wk, data = movie_df[cum_theaters>1,]))

```

### Dataset Sources and Structure
The dataset is a compilation of film data scrapped from [Box Office Mojo](http://www.boxofficemojo.com/), and [Metacritic](http://www.metacritic.com). The data set is `r dim(movie_df)[1]` observations of a single 'movie week' (a week for a single film), including `r length(unique(movie_df[, title]))` unique titles. This analysis has been limited to films in reasonably wide release (those that at some point were in over 1000 theaters), as those are titles people will recognize (a huge number of obscure films have a limited releases each year).

Box Office Mojo had data on the film title, distributor, release date, genre, runtime, rating, budget, domestic gross, weekly grosses, theaters per weekly, days per weekly, week of the year, and acting talent.

Metacritic contained average critic reviews, average audience reviews and individual critic reviews (critics on a 100 point scale, audience on a 10 point one).

Note: for brevity, max indicates a maximum individual data point, cum represents cumulative measures, med is a median and avg is an average. As there are a large number of variables (many related), this analysis will only tackle a subset. Additionally, while production budget is seemingly important, I am missing so many observations that I decided not to use it. 

```{r, tidy = TRUE}
#display the structure of the movie datatable
str(movie_df)

```

# Univariate Exploration

## Key Film Performance Measures

I was primarily interested in better understanding U.S. domestic boxoffice performance for the films in the sample. Performance can be measured a number of different ways, but given the granularity of the data I have, the most meaningful is probably a measure of efficiency, which I call daily theater efficiency. 

Daily theater efficiency is a derived feature and is an expression of dollars produced per theater.  It allows a theater owner to assess whether he should show one movie or another. All other things equal, it is always better to show more films with higher daily theater efficiency. 

To go a little further, it is easy to see that, for any film, the $\small{weekly\ gross=total\ tickets \times average\ price}$.  A more complete breakout of $\small{total\ tickets=\frac{screens}{theater} \times theaters \times \frac{shows}{day} \times \frac{tickets}{show} \times days}$. We have some limitations in our data, so we'll just use theaters and days as a stand in.  To get daily theater efficiency, we just calculate $\small{\frac{weekly\ gross}{(theaters \times days)}}$ which is a proxy for how often shows are played, how many screens a film is on and how full the shows are if we assume price is constant across films/screenings (obviously not true, but we don't have better data).

```{r echo=FALSE, Main_Feature_Plots, fig.align = 'center', fig.width = 12, fig.height = 6, htmlcap = 'Fig. 1: Film weekly grosses, theaters, daily theater efficiency; standard and log transformed'}

# I tend to use 1 and 99 pct quantile cutoffs for most graphs to limit
# long tails and keep the view focused on the bulk of data

#find chart range and plot weekly gross
gross_range <- get_chart_range(movie_df, 'weekly_gross', .01, .975)
p1 <- ggplot(aes(x = weekly_gross), data = movie_df) +
  geom_bar(binwidth = 250000, fill = 'navyblue') +
  coord_cartesian(xlim = c(gross_range))

#find chart range and plot weekly theaters
theater_range <- get_chart_range(movie_df, 'weekly_theaters', .01, .99)
p2 <- ggplot(aes(x = weekly_theaters), data = movie_df) +
  geom_bar(binwidth = 100, fill = 'navyblue') +
  coord_cartesian(xlim = c(theater_range))

#find chart range and plot daily theater efficiency
eff_range <- get_chart_range(movie_df, 'daily_theater_eff', .01, .99)
p3 <- ggplot(aes(x = daily_theater_eff), data = movie_df) +
  geom_bar(binwidth = 100, fill = 'navyblue') +
  coord_cartesian(xlim = c(eff_range))

# log transform weekly gross plot
p4 <- ggplot(aes(x = weekly_gross), data = movie_df[!is.na(weekly_gross), ]) +
  geom_bar(binwidth = .2, fill = 'navyblue') +
  scale_x_log10() +
  coord_cartesian(xlim = c(gross_range)) +
  xlab('log10(weekly_gross)')

# log transform weekly theater plot
p5 <- ggplot(aes(x = weekly_theaters), data = movie_df) +
  geom_bar(binwidth = .1, fill = 'navyblue') +
  scale_x_log10() +
  coord_cartesian(xlim = c(theater_range)) +
  xlab('log10(weekly_theaters)')

# log transform daily theater efficiency plot
p6 <- ggplot(aes(x = daily_theater_eff), data = movie_df) +
  geom_bar(binwidth = .1, fill = 'navyblue') +
  scale_x_log10() +
  coord_cartesian(xlim = c(eff_range)) +
  xlab('log10(daily_theater_eff)')

grid.arrange(p1, p2, p3, p4, p5, p6, ncol = 3,
             top = "Key Metrics for Weekly Film Performance")

#clean plots from memory (they're big)
rm(p1, p2, p3, p4, p5, p6)
```

A couple thoughts:

* All of these look like they are potnetially exponential distributions that would benefit from a log transform when analyzing
* Weekly gross and weekly theaters have interesting bi-modal distributions once log transformed.

## Potential Associated Measures

Many data points are likely germane to measures of theater efficiency.  Obviously, for daily efficiency, I'll need to examine theater counts and weekly grosses. 
See the proceeding charts for my thoughts.

### Descriptive Measures

There are an additional handful of easy descriptive measures to look at: Seasonality is important in movie attendance, so I will look at week of year data.  The time a film has been out is also relevant (novelty is important).  Similarly, genre, rating and runtime are easy to examine.

```{r echo = FALSE, Descriptive_Metrics, fig.align = 'center', fig.width = 12, fig.height = 6, htmlcap = 'Fig. 2: Films by week of year, genre (limited to top 20), MPAA rating, and runtime.<br>With the exception of the week of year, these are all invariate by week, so unique films are plotted.'}

#find range and plot week of year
week_range <- get_chart_range(movie_df, 'week', 0, 1)
p7 <- ggplot(aes(x = as.numeric(week)), data = movie_df[!is.na(week), ]) +
  geom_bar(binwidth = 1, fill = 'navyblue') + 
  scale_x_discrete(breaks = seq(week_range[1],week_range[2], 5))

#generate top genres by movie releases to simplify plot
genres_dat <- unique_films(movie_df, 'genre')
top_genres <- names(sort(xtabs(~genre, genres_dat), decreasing = T)[1:20])

# plot top genres
p8 <- ggplot(aes(x = genre), data = genres_dat[genre %in% top_genres, ]) +
  geom_bar(binwidth = 1, fill = 'navyblue') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0))

#generate unique ratings by movie releases to simplify plot
rating_dat <- unique_films(movie_df, 'mpaa_rating')

#plot mpaa rating
p9 <- ggplot(aes(x = mpaa_rating), data = rating_dat[!is.na(mpaa_rating), ]) +
  geom_bar(binwidth = 1, fill = 'navyblue')

#generate runtime by movie releases
runtime_dat <- unique_films(movie_df, 'runtime')

#plot runtime
p10 <- ggplot(aes(x = runtime), data = runtime_dat[!is.na(runtime), ]) +
  geom_bar(binwidth = 2, fill = 'navyblue')

grid.arrange(p7, p8, p9, p10, nrow = 2, top = 'Simple Descriptive Measures')

#clean plots from memory (they're big)
rm(p7, p8, p9, p10)
```

A few quick observations are in order:

* On the weekly chart, we see that weeks 1 and 53 have smaller counts of film weeks - this is likely due to the fact that in most years, these are partial weeks   
* Again, on the weekly chart, we see that fewer film weeks are counted during late Spring / Summer (weeks 23 - 32) and late Fall (weeks 47 - 51).  These periods correspond with tent-pole picture releases and it may be that more theaters are occupied by a few large films. As evidence, a quick series of t-tests reveals that films in these periods tend to be larger both by theater counts and weekly grosses:

```{r echo = FALSE, tidy = TRUE}
tentpoles <- c(23:32, 47:51)

tentpole_theaters <- movie_df[as.numeric(week) %in% tentpoles,
                              weekly_theaters]

non_tentpole_theaters <- movie_df[!(as.numeric(week) %in% tentpoles),
                                    weekly_theaters]
# t-test comparing weekly theaters for films in tentpole season
t.test(tentpole_theaters, non_tentpole_theaters, alternative = 'greater')

tentpole_gross <- movie_df[as.numeric(week) %in% tentpoles,
                           weekly_gross]

non_tentpole_gross <- movie_df[!(as.numeric(week) %in% tentpoles),
                               weekly_gross]

# t-test comparing weekly grosses for films in tentpole season
t.test(tentpole_gross, non_tentpole_gross, alternative = 'greater')


```
* There is almost always a comedy playing somewhere
* PG-13 is by far the most common rating on a film week basis
* Runtime is about what one expects - generally between `r quantile(runtime_dat[, runtime], .25, na.rm = T)` and `r quantile(runtime_dat[, runtime], .75, na.rm = T)` mins (25th - 75th quantiles)

### Quality Measures - Critics and Audience

Other meaningful measures are a little harder to wrap one's head around.  Quality probably has something to do with film critic and audience assessments, but may also be related to dispersion of opinion (think of 'thought provoking / controversial films'). Count of critic reviews may have something to do with scale of release (e.g., do studios / distributors think it is a 'hit'). Again, these are invariate by week, so are presented on a unique film basis.

```{r echo = FALSE, Quality_Critics, fig.width = 12, fig.height = 6, htmlcap = 'Fig. 3: Average critic score, count of Metacritic critic reviews, critic score interquartile range (25-75), and audience score.<br>Again, unique by film.'}

# plot critics_avg scores from unique films
critics_avg_dat <- unique_films(movie_df, 'critics_avg')
p11 <- ggplot(aes(x = critics_avg), data = critics_avg_dat) +
  geom_bar(binwidth = 2, fill = 'navyblue')
  
# plot count_critic scores from unique films
count_critics_dat <- unique_films(movie_df, 'count_critics')
p12 <- ggplot(aes(x = count_critics), data = count_critics_dat) +
  geom_bar(binwidth = 1, fill = 'navyblue')

# plot critic_IQR scores from unique films
critics_IQR_dat <- unique_films(movie_df, 'critics_IQR')
p13 <- ggplot(aes(x = critics_IQR), data = critics_IQR_dat) +
  geom_bar(binwidth = 2, fill = 'navyblue')

##plot audience_avg scores from unique films
audience_avg_dat <- unique_films(movie_df, 'audience_avg')
p14 <- ggplot(aes(x = audience_avg), data = audience_avg_dat) +
  geom_bar(binwidth = 1, fill = 'navyblue')

grid.arrange(p11, p12, p13, p14, nrow = 2,
             top = 'Critic and Audience Approval Measures')

#clean plots from memory (they're big)
rm(p11, p12, p13, p14)
```

Again, some observations:

* These all seem fairly well behaved
* Audience scores and critic counts may be a little skewed, but these distributions have a nice shape to them without any manipulation  
* The citics interquartile range (critics_IQR) chart may be bi-modal, which would be interesting and would foot with the idea that there are two classes of films: controversial and non-controversial. I'm not cetain I have a good way to examine that item yet

### Quality Measures - Cast

Cast may also have a lot to do with quality and, hence, daily theater efficiency. I contrived a variety of metrics to determine quality through cast, these include the counts of the number of pictures that actors are in (it is reasonable to think that better actors may get invited to do more films) and measures of connectedness from the [igraph](http://igraph.org/r/) package - specifically degrees (a count of the connections of one actor node to others on a graph) and betweeness (a measure of how many paths between other actors pass through an actor's node on a graph). Note: the actor graph was developed using the full data set of `r length(movie_data)` unique titles.

```{r echo = FALSE, Quality_Cast, fig.width = 12, fig.height = 6, htmlcap = 'Fig. 4: Cumulative pictures by cast, cumulative degrees of cast, and betweeness of cast.<br>Once more, unique by film.'}

#find range and plot cumulative cast pictures
pics_dat <- unique_films(movie_df, 'talent_cum_pics')
pics_range <- get_chart_range(pics_dat, 'talent_cum_pics', 0, .99)
p15 <- ggplot(aes(x = talent_cum_pics), data = pics_dat) +
  geom_bar(binwidth = 5, fill = 'navyblue') + 
  coord_cartesian(xlim = c(pics_range))

#find range and plot cumulative cast degree
deg_dat <- unique_films(movie_df, 'talent_cum_deg')
deg_range <- get_chart_range(deg_dat, 'talent_cum_deg', .01, .99)
p16 <- ggplot(aes(x = talent_cum_deg), data = deg_dat) +
  geom_bar(binwidth = 25, fill = 'navyblue') + 
  coord_cartesian(xlim = c(deg_range))

#find range and plot cumulative cast betweeness
bet_dat <- unique_films(movie_df, 'talent_cum_bet')
bet_range <- get_chart_range(bet_dat, 'talent_cum_bet', .01, .99)
p17 <- ggplot(aes(x = talent_cum_bet), data = bet_dat) +
  geom_bar(binwidth = 2500, fill = 'navyblue') + 
  coord_cartesian(xlim = c(bet_range))
 
#plot log cumulative cast pics
p18 <- ggplot(aes(x = talent_cum_pics), data = pics_dat) +
  geom_bar(binwidth = .025, fill = 'navyblue') + 
  coord_cartesian(xlim = c(pics_range)) +
  scale_x_log10() +
  xlab('log10(talent_cum_pics)')

#plot log cumulative cast degrees
p19 <- ggplot(aes(x = talent_cum_deg), data = deg_dat) +
  geom_bar(binwidth = .025, fill = 'navyblue') + 
  coord_cartesian(xlim = c(deg_range)) +
  scale_x_log10() +
  xlab('log10(talent_cum_deg)')

#plot log cumulative cast betweeness
p20 <- ggplot(aes(x = talent_cum_bet), data = bet_dat) +
  geom_bar(binwidth = .05, fill = 'navyblue') + 
  coord_cartesian(xlim = c(bet_range)) +
  scale_x_log10() +
  xlab('log10(talent_cum_bet)')

grid.arrange(p15, p16, p17, p18, p19, p20, nrow = 2, 
             top = 'Cumulative Cast Measures')

#clean plots from memory (they're big)
rm(p15, p16, p17, p18, p19, p20)
```

A few quick thoughts on the cumulative talent measures:

* All three distributions have positive skew and, given the way measures of success, wealth, etc. tend to be distributed in human populations, these may be exponential funcitons improved by log transforming
* After transforming, the skewness on all distributions shifts, but it is not really clear this improved anything

### Competition

Finally, competition may have something to do with a film's performance. In any given week, a movie is competing against other movies for a share of the potential audience wallet and attention.  I derive measures of the cumulative box office, theater counts and critics score averages of all films in a given week, which may allow me to look at the relative level of competition a film faced.

```{r echo = FALSE, Competition, fig.width = 12, fig.height = 3, htmlcap = 'Fig. 5: Gross competative box office, cumulative competative critic scores,<br>and cumulative competative theater counts for a given year and week.'}

#find range and plot competition weekly gross
box_weeks <- movie_df[, list(comp_box = sum(weekly_gross, na.rm = T)),
                         by = list(year, week)]
comp_box_range <- get_chart_range(box_weeks, 'comp_box', .01, .95)
p21 <- ggplot(aes(x = comp_box), data = box_weeks) +
  geom_bar(binwidth = 10000000, fill = 'navyblue') + 
  coord_cartesian(xlim = c(comp_box_range))

#find range and plot competition critic scores
critic_weeks <- movie_df[,list(comp_critic = sum(critics_avg, na.rm = T)),
                             by = list(year, week)]
comp_critic_range <- get_chart_range(critic_weeks, 'comp_critic', .01, .99)
p22 <- ggplot(aes(x = comp_critic), data = critic_weeks) +
  geom_bar(binwidth = 100, fill = 'navyblue') + 
  coord_cartesian(xlim = c(comp_critic_range))

#find range and plot competition theaters
theater_weeks <- movie_df[,list(comp_theater = sum(weekly_theaters, na.rm = T)),
                          by = list(year, week)]
comp_theater_range <- get_chart_range(theater_weeks, 'comp_theater', .01, .99)
p23 <- ggplot(aes(x = comp_theater), data = theater_weeks) +
  geom_bar(binwidth = 1000, fill = 'navyblue') + 
  coord_cartesian(xlim = c(comp_theater_range))

grid.arrange(p21, p22, p23, nrow = 1, top = 'Competative Measures')

#clean plots from memory (they're big)
rm(p21, p22, p23)
```

Thoughts on competition:

* These variables are all pretty well behaved, though competative box is has some skew
* There are some weeks with low counts early in the examined period, this is porbably because films released prior to 11/2003 still occupied theaters for a couple months, but are absent from my statistics 

# Bivariate Exploration

## Novelty / Recency

New releases are a big deal. It is pretty easy to see what I mean by plotting our key film metrics (weekly gross, weekly theaters, daily theater eff) by week of a film's release. We'll see that the early weeks of a film's release dominate grosses and theater counts. Given what we learned about the shape of the distributions before, I show them all log transformed. I limit the scope to the first two months of release and plot the median and correlation so that we'll get a sense for the linear relationship. Relative week was omitted from univariate analysis as it would have been nonsensical.

```{r echo=FALSE, Novelty_Plots, fig.width = 12, fig.height = 4, htmlcap = "Fig. 6: Weekly domestic box office, weekly theater counts and daily theater efficiency<br>log10 transformed and plotted by relative week of a film's release. Correlation overlaid in black."}

#make correlation note
c1 <- plot_cor(movie_df[, log10(weekly_gross)], movie_df[, relative_week])

#plot log weekly gross vs relative week
p24 <- ggplot(aes(x = relative_week, y = weekly_gross),
              data = movie_df[!is.na(weekly_gross), ]) +
  geom_point(alpha = .25, position = position_jitter(h = 0), color = 'navyblue') +
  coord_cartesian(xlim = c(.5, 8.5)) +
  geom_line(stat = 'summary', fun.y = 'median', size = 1) +
  scale_y_log10() +
  ylab('log10(weekly_gross)') +
  geom_text(data = NULL, x = 6, y = 8, label = c1, size = 4)


#make correlation note
c2 <- plot_cor(movie_df[, log10(weekly_theaters)], movie_df[, relative_week])

#plot log weekly theaters vs relative week
p25 <- ggplot(aes(x = relative_week, y = weekly_theaters),
              data = movie_df[!is.na(weekly_theaters), ]) +
  geom_point(alpha = .25, position = position_jitter(h = 0), color = 'navyblue') +
  coord_cartesian(xlim = c(.5, 8.5)) +
  geom_line(stat = 'summary', fun.y = 'median', size = 1) +
  scale_y_log10() +
  ylab('log10(weekly_theaters)') +
  geom_text(data = NULL, x = 3, y = 1, label = c2, size = 4)

#make correlation note
c3 <- plot_cor(movie_df[, log10(daily_theater_eff)], movie_df[, relative_week])

p26 <- ggplot(aes(x = relative_week, y = daily_theater_eff),
              data = movie_df[!is.na(daily_theater_eff), ]) +
  geom_point(alpha = .25, position = position_jitter(h = 0), color = 'navyblue') +
  coord_cartesian(xlim = c(.5, 8.5)) +
  geom_line(stat = 'summary', fun.y = 'median', size = 1) +
  scale_y_log10() +
  ylab('log10(daily_theater_eff)') +
  geom_text(data = NULL, x = 6, y = 4.5, label = c3, size = 4)

grid.arrange(p24, p25, p26, nrow = 1, 
             top = 'Key Film Metrics by Relative Week of Release')

#clean plots from memory (they're big)
rm(p24, p25, p26)

```

Some observations:

* Novelty is very imortant: all of these have a pretty strong linear relationship between time a film's been released and the variable
* None of these relationships, even when log transformed, are perfectly linear (it is a complicated relationship, I have tried some other transforms on both x and y variables with only marginal improvement - these are not shown)
* There is not much change between theater counts during the first and second weeks of a film's release. This is possibly an artifact of how distribution is contracted: distributors and theater chains typically have an agreement on the number of screens for the first two weeks of a film's release
* Daily theater efficiency is the least linearly related to relative week - perhaps this is because we remove some of the relationship during construction (weekly theaters are have a substantial relationship with relative week and we're dividing that out of the weekly gross)

## Box Office Seasonality

I mentioned earlier on that seasonality measured by relative week of release would be important.  I provide my evidence in the following plots. I plot individual film weeks (top row) and the aggregates we calculated for our competative measures (bottom). While we only have 12 years of data for the aggregates, there are some clear trends.

```{r echo=FALSE, Seasonal_Plots, fig.width = 12, fig.height = 6, htmlcap = "Fig. 7: Weekly domestic box office, weekly theater counts and critic averages.<br>Individual films (top) and competative aggregates (bottom) plotted by week of year. Green dot denotes an average, blue bar is median."}

#find chart range and plot weekly gross
week_gross_range <- get_chart_range(movie_df, 'weekly_gross', .01, .95)
p27 <- ggplot(aes(x = week, y = weekly_gross), 
              data = movie_df[!is.na(weekly_gross), ]) +
  geom_boxplot(color = 'navyblue') +
  coord_cartesian(ylim = week_gross_range) +
  stat_summary(fun.y=mean, geom="point", size=2, color = 'darkgreen') + 
  scale_x_discrete(breaks = seq(week_range[1]-1,week_range[2], 10))

#find chart range and plot weekly_theaters
week_theater_range <- get_chart_range(movie_df, 'weekly_theaters', .01, .99)
p28 <- ggplot(aes(x = week, y = weekly_theaters), 
              data = movie_df[!is.na(weekly_theaters), ]) +
  geom_boxplot(color = 'navyblue') +
  coord_cartesian(ylim = week_theater_range) +
  stat_summary(fun.y=mean, geom="point", size=2, color = 'darkgreen') + 
  scale_x_discrete(breaks = seq(week_range[1]-1,week_range[2], 10))

#find chart range and plot critic_avg during week of release by week
week_critic_range <- get_chart_range(movie_df, 'critics_avg', .01, .99)
p29 <- ggplot(aes(x = week, y = critics_avg), 
              data = movie_df[!is.na(critics_avg), ]) +
  geom_boxplot(color = 'navyblue') +
  coord_cartesian(ylim = week_critic_range) +
  stat_summary(fun.y=mean, geom="point", size=2, color = 'darkgreen') + 
  scale_x_discrete(breaks = seq(week_range[1]-1,week_range[2], 10))

#find chart range and plot critic_avg during week of release by week
comp_box_range <- get_chart_range(box_weeks, 'comp_box', .005, .995)
p30 <- ggplot(aes(x = week, y = comp_box), data = box_weeks) +
  geom_boxplot(color = 'navyblue') +
  coord_cartesian(ylim = comp_box_range) + 
  scale_x_discrete(breaks = seq(week_range[1]-1,week_range[2], 10))

#find chart range and plot critic_avg during week of release by week
comp_theater_range <- get_chart_range(theater_weeks, 'comp_theater', .005, .995)
p31 <- ggplot(aes(x = week, y = comp_theater), data = theater_weeks) +
  geom_boxplot(color = 'navyblue') +
  coord_cartesian(ylim = comp_theater_range) + 
  scale_x_discrete(breaks = seq(week_range[1]-1,week_range[2], 10))

#find chart range and plot critic_avg during week of release by week
comp_critic_range <- get_chart_range(critic_weeks, 'comp_critic', .005, .995)
p32 <- ggplot(aes(x = week, y = comp_critic), data = critic_weeks) +
  geom_boxplot(color = 'navyblue') +
  coord_cartesian(ylim = comp_critic_range) + 
  scale_x_discrete(breaks = seq(week_range[1]-1,week_range[2], 10))

grid.arrange(p27, p28, p29, p30, p31, p32, nrow = 2,
             top = 'Seasonal Impact: Individual Films and Competative Aggregates')

#clean plots from memory (they're big)
rm(p27, p28, p29, p30, p31, p32)

```

A few things worth mentioning:

* During the Summer and late Fall, we see that the average individual film gross goes up while the median stays the same - this means a few very large films (tentpoles/blockbusters) are dominating th numbers. Confirmation can be found in theater counts (averages go up, while medians stay low)
* We see in the aggregates that Summer and late Fall are a huge periods for the weekly gross overall, but given that theater counts actually fall in agregate, we can posit that fewer individual films may be occupying more screens in individual theaters (since theaters are probably fairly fixed)
* An interesting story is told by our critics, which foots with popular notions of the film calendar: during Summer, quality is high for the few blockbuster films released (high average scores, low competative aggregates), whereas late Fall is a period of higher average critic scores and normal levels in aggregate scores, so a higher than usual number of 'Oscar-bait' quality films are out
* Late Summer/early Fall see low boxoffice on an individual and aggregate basis with high theater counts and low individual critic averages - this means a large number of pretty bad films are in theaters and daily theater efficiency should be lower

## Film Category: Genre and Rating

I want to take a little time to look into performance by genre and rating.  I have a sense that it matters - certainly the prevalence of large G-rated computer animated films and Summer PG-13-rated superhero flicks makes me think it should be relavent.  I plot the key metrics against genre and rating below.

```{r echo = FALSE, Category_Plots, fig.width = 12, fig.height = 6, htmlcap = "Fig. 8: Total domestic box office, cumulative theater counts and daily theater efficiency by category of film.<br>Unique film values. Green dot denotes mean. Blue bar denotes median."}

#add grosses to top genres
gross_dat <- unique_films(movie_df, 'gross')
genre_gross_dat <- merge(genres_dat, gross_dat, by = 'title')

# plot grosses for top genres
genre_gross_range <- get_chart_range(genre_gross_dat, 'gross', .01, .99)
p33 <- ggplot(aes(y = gross, x = genre),
             data = genre_gross_dat[genre %in% top_genres, ]) +
  geom_boxplot(color = 'navyblue') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0)) +
  coord_cartesian(ylim = genre_gross_range) +
  stat_summary(fun.y=mean, geom="point", size=2, color = 'darkgreen')

#add cumulative theaters to top genres
cum_theater_dat <- unique_films(movie_df, 'cum_theaters')
genre_theater_dat <- merge(genres_dat, cum_theater_dat, by = 'title')

# find range and plot total theaters for top genres
genre_theater_range <- get_chart_range(genre_theater_dat, 
                                   'cum_theaters', .01, .99)
p34 <- ggplot(aes(y = cum_theaters, x = genre),
             data = genre_theater_dat[genre %in% top_genres, ]) +
  geom_boxplot(color = 'navyblue') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0)) +
  coord_cartesian(ylim = genre_theater_range) +
  stat_summary(fun.y=mean, geom="point", size=2, color = 'darkgreen')

# build genre efficiency measure (to keep consistant, 
# multiplied by 6 as each theater is a week)
genre_eff_dat <- merge(genre_gross_dat, genre_theater_dat, by = c('title', 'genre'))
genre_eff_dat[, daily_theater_eff:= gross / (cum_theaters * 6)]

# find range and plot efficiencies for top genres
genre_eff_range <- get_chart_range(genre_eff_dat, 
                                   'daily_theater_eff', .01, .99)
p35 <- ggplot(aes(y = daily_theater_eff, x = genre),
             data = genre_eff_dat[genre %in% top_genres, ]) +
  geom_boxplot(color = 'navyblue') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0)) +
  coord_cartesian(ylim = genre_eff_range) +
  stat_summary(fun.y=mean, geom="point", size=2, color = 'darkgreen')

#make unique rating data
rating_gross_dat <- merge(rating_dat, gross_dat, by = 'title')

# plot grosses for top ratings
rating_gross_range <- get_chart_range(rating_gross_dat, 'gross', .01, .99)
p36 <- ggplot(aes(y = gross, x = mpaa_rating),
             data = rating_gross_dat) +
  geom_boxplot(color = 'navyblue') +
  coord_cartesian(ylim = rating_gross_range) +
  stat_summary(fun.y=mean, geom="point", size=2, color = 'darkgreen')

#add cumulative theaters to top ratings
rating_theater_dat <- merge(rating_dat, cum_theater_dat, by = 'title')

# find range and plot total theaters for top ratings
rating_theater_range <- get_chart_range(rating_theater_dat, 
                                   'cum_theaters', .01, .99)
p37 <- ggplot(aes(y = cum_theaters, x = mpaa_rating),
             data = rating_theater_dat) +
  geom_boxplot(color = 'navyblue') +
  coord_cartesian(ylim = rating_theater_range) +
  stat_summary(fun.y=mean, geom="point", size=2, color = 'darkgreen')

# build rating efficiency measure (to keep consistant, 
# multiplied by 6 as each theater is a week)
rating_eff_dat <- merge(rating_gross_dat, rating_theater_dat,
                        by = c('title', 'mpaa_rating'))
rating_eff_dat[, daily_theater_eff:= gross / (cum_theaters * 6)]

# find range and plot efficiencies for top ratings
rating_eff_range <- get_chart_range(rating_eff_dat, 
                                   'daily_theater_eff', .01, .99)
p38 <- ggplot(aes(y = daily_theater_eff, x = mpaa_rating),
             data = rating_eff_dat) +
  geom_boxplot(color = 'navyblue') +
  coord_cartesian(ylim = rating_eff_range) +
  stat_summary(fun.y=mean, geom="point", size=2, color = 'darkgreen')

grid.arrange(p33, p34, p35, p36, p37, p38, nrow = 2,
             top = 'Genre, Ratings and Film Performance Metrics')

#clean plots from memory (they're big)
rm(p33, p34, p35, p36, p37, p38)


```

Quick commentary:

* The genre results kind of mirror my own take as to what a blockbuster looks like - we see Action / Adventure has both the largest total gross, the greatest per theater efficiency and one of the greatest cumulative theater week counts
* Animation, Fantasy and Sci-Fi Action are all also potential huge films
* If theaters could make frictionless tradeoffs among films, I would expect our efficiency measure to look fairly flat across genres (as it does for ratings) - the fact that we can see a lot of variation for certain genres implies something (may be contracts or seasonality) prevents that
* Horror has a reputation for high ROI to film  producers (they're cheap to make), but we can see that efficiency is also low, so it may be hard to get those films in theaters when other fare is out
* We see that most genres have positive skew for grosses (higher mean than median), so unusual films have the potential to make a fair amount of money in most categories
* Family friendly G-rated pictures are the most rewarding ratign category; perhaps this is due to them having the largest addressable audience and the fact that more tickets are sold when a family attends as a group - unfortunately I don't have data to test these ideas

Given our discovery that effeciency is not consistent across genres while it is fairly close among ratings, I thought it may merit investigating the intersection of genre.  I will plot what amounts to a crosstab of rating and genre and investigate any seasonality that may prevent theaters from making the tradeoffs that create uniform efficiency across genres. 

```{r echo = FALSE, Category_Cross, fig.width = 12, fig.height = 12, htmlcap = "Fig. 9: Genere by rating and seasonal charts showing genre and rating by week of year.<br>Top 20 most frequent genres examined (top). Seasonal genre chart limited to top four to assist legibility (middle)."}

genre_rating_dat <- merge(genres_dat, rating_dat, by = 'title')
p39 <- ggplot(aes(x = genre, fill = mpaa_rating),
              data = genre_rating_dat[genre %in% top_genres, ]) +
  geom_bar(position = 'fill') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0),
        legend.position = 'right') +
  scale_fill_brewer(type = 'qual', palette = 'Set2')

week_dat <- unique_films(movie_df, 'week')
genre_week_dat <- merge(genres_dat, week_dat, by = 'title')
p40 <- ggplot(aes(x = week, fill = genre),
              data = genre_week_dat[genre %in% top_genres[1:4], ]) +
  geom_bar(position = 'dodge') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0),
        legend.position = 'right') +
  scale_fill_brewer(type = 'qual', palette = 'Accent') + 
  scale_x_discrete(breaks = seq(week_range[1]-1,week_range[2], 10))

rating_week_dat <- merge(rating_dat, week_dat, by = 'title')
p41 <- ggplot(aes(x = week, fill = mpaa_rating),
              data = rating_week_dat) +
  geom_bar(position = 'dodge') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0),
        legend.position = 'right') +
  scale_fill_brewer(type = 'qual', palette = 'Set2') + 
  scale_x_discrete(breaks = seq(week_range[1]-1,week_range[2], 10))

grid.arrange(p39, p40, p41, nrow = 3,
             top = 'Genre and Rating: Category and Calendar')

rm(p39, p40, p41)

```

Notes:

* Certain genres are heavily dominated by specific ratings: Family Adventure is PG; Romance, Action / Adventure, Romantic Comedy and Sci-Fi Action are all heavily PG-13; Horror and Drama / Thriller are mostly R;
* G-rated films are rare: Animation and Family Comedy are the only genres with any G-films
* As I suspected, seasonal patterns exist in genre: Horror peaks in mid-Fall (to co-incide with Halloween); Animation is strong in the Summer, but peaks in the family-friendly period around Thanksgiving; Dramas are few and far between during the Summer, gradually increasing up through award season in the Spring; Comedy is always common, but peaks in late-Summer and late-Spring (periods with low grosses and theater efficiency), potentially playing the role of 'filler' fare
* Ratings are seasonal, but less so: PG and G-rated films are out in low, constant levels; PG-13 is usually common, but has some share stolen by R-rated films going into Halloween

```{r echo = FALSE}
# 
# p27 <- ggplot(aes(x = week, y = comp_box), data = box_weeks) +
#   geom_boxplot(color = 'navyblue')
# 
# p28 <- ggplot(aes(x = week, y = comp_critic), data = critic_weeks) +
#   geom_boxplot(color = 'navyblue')
# 
# p29 <- ggplot(aes(x = week, y = comp_theater), data = theater_weeks) +
#   geom_boxplot(color = 'navyblue')
# 
# #construct film specific measure of theater efficiency - I multiply cum_theaters
# #by six since all theaters are on a theater/week basis, given the univariate
# #distribution, from before, this variable will be log transformed
# movie_df[,cum_theater_eff := log10(gross / (cum_theaters * 6))]
# 
# #build dataset of features invariate by week (unique to a film)
# unifilm_dat <- unique(movie_df[,list(cum_theater_eff, runtime,
#                                      critics_avg, count_critics, critics_IQR,
#                                      audience_avg, talent_cum_pics,
#                                      talent_cum_deg, talent_cum_bet)])
# #build scatterplot matrix - factor variables not used here due to legibility
# ggpairs(unifilm_dat)
# 
# #build dataset of features invariate by week (unique to a film)
# timedfilm_dat <- unique(movie_df[,list(log10(weekly_gross), log10(weekly_theaters), log10(daily_theater_eff), relative_week, comp_week_cash, comp_week_critics, comp_week_theaters)])
# 
# ggpairs(timedfilm_dat)

```


# Bivariate Analysis

### Talk about some of the relationships you observed in this part of the investigation. How did the feature(s) of interest vary with other features in the dataset?

### Did you observe any interesting relationships between the other features (not the main feature(s) of interest)?

### What was the strongest relationship you found?




# Multivariate Plots Section

```{r echo=FALSE, Multivariate_Plots}

```

# Multivariate Analysis

### Talk about some of the relationships you observed in this part of the investigation. Were there features that strengthened each other in terms of looking at your feature(s) of interest?

### Were there any interesting or surprising interactions between features?

### OPTIONAL: Did you create any models with your dataset? Discuss the strengths and limitations of your model.

------

# Final Plots and Summary

### Plot One
```{r echo=FALSE, Plot_One}

```

### Description One


### Plot Two
```{r echo=FALSE, Plot_Two}

```

### Description Two


### Plot Three
```{r echo=FALSE, Plot_Three}

```

### Description Three

------

# Reflection
